import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ datas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          merhaba
        </div>
        {datas.map((data, index) => {
          return (
            <span key={index}>{data.id}</span>
          )
        })}
      </main>


    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json()

  console.log(data)
  return {
    props: { datas: data }
  }
}
