import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const [messages, setMessages] = useState([])
  const [isLoading, setLoading] = useState(false)
  const [value, setValue] = useState("")
  const [apiTrigger, setApiTrigger] = useState(false)
  const handlePost = () => {
    console.log(value)

    fetch('api/messages', { method: 'POST', body: value })
      .then((res) => {
        setValue("")
        setApiTrigger(!apiTrigger)
      })

  }

  useEffect(() => {
    setLoading(true)
    fetch('api/messages')
      .then((res) => res.json())
      .then((res) => {
        setMessages(res.data)
        setLoading(false)
      })
  }, [apiTrigger])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          merhaba
        </div>
        {messages.map((message, index) => {
          return (
            <span key={index}>{message.name}</span>
          )
        })}

        <input onChange={(event) => setValue(event.target.value)} value={value}></input>
        <button onClick={() => handlePost()}>Kaydet</button>
      </main>


    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json()

  return {
    props: { datas: data }
  }
}