import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const [messages, setMessages] = useState([])
  const [isLoading, setLoading] = useState(false)
  const [value, setValue] = useState("")
  const [apiTrigger, setApiTrigger] = useState(false)


  const handlePost = () => {
    fetch('api/messages', { method: 'POST', body: value })
      .then((res) => {
        setValue("")
        setApiTrigger(!apiTrigger)
      })
  }

  const handleEdit = (dataID) => {
    const val = document.getElementById("input" + dataID).value

    const payload = JSON.stringify({
      id: dataID,
      name: val
    })

    fetch('api/messages', { method: 'PUT', body: payload })
      .then((res) => {
        setApiTrigger(!apiTrigger)
      })
  }

  const handleDelete = (dataID) => {
    fetch('api/messages', { method: 'DELETE', body: dataID })
      .then((res) => {
        setApiTrigger(!apiTrigger)
      })
  }

  useEffect(() => {
    setLoading(true)
    fetch('api/messages')
      .then((res) => res.json())
      .then((res) => {
        setMessages(res.data)
        setLoading(false)
      })
  }, [apiTrigger])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {messages.map((message, index) => {
          return (
            <div style={{ marginTop: 10 }} key={index}>
              <span>
                {index + 1}.
              </span>

              <span>
                <input id={"input" + message.id} defaultValue={message.name}></input>
              </span>
              <span>

                <button onClick={() => handleEdit(message.id)}>edit</button>
              </span>
              <span>

                <button onClick={() => handleDelete(message.id)}>delete</button>
              </span>
              <span>
                id: {message.id}
              </span>
            </div>
          )
        })}

        <input style={{ marginTop: 100 }} onChange={(event) => setValue(event.target.value)} value={value}></input>
        <button onClick={() => handlePost()}>Gönder</button>
      </main>


    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json()

  return {
    props: { datas: data }
  }
}